name: Meta Gen

on:
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday 2am
  workflow_dispatch:

jobs:
  meta-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run meta-gen
        env:
          GSC_CREDENTIALS: ${{ secrets.GSC_CREDENTIALS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WARPMETRICS_API_KEY: ${{ secrets.WARPMETRICS_API_KEY }}
          GSC_CLIENT_ID: ${{ secrets.GSC_CLIENT_ID }}
          GSC_CLIENT_SECRET: ${{ secrets.GSC_CLIENT_SECRET }}
        run: |
          echo "$GSC_CREDENTIALS" > .gsc-credentials.json
          npx meta-gen run --threshold 3.0 --max 50

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: improve meta descriptions'
          branch: meta-gen/weekly-update
          delete-branch: true
          title: 'SEO: Improve meta descriptions'
          body: |
            ## Meta Description Improvements

            Generated by @warpmetrics/meta-gen.

            ### What changed
            - Collected feedback on previously generated descriptions
            - Analyzed patterns from high-CTR descriptions
            - Generated improved descriptions for low-CTR pages

            See `src/meta.json` for changes.

            ### Review checklist
            - [ ] Descriptions match brand voice
            - [ ] No typos or grammatical errors
